=== Saturn-Labs/UnityFunkin/Assets/Resources/Schemas/mod_descriptor_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "A UnityFunkin mod descriptor.",
	"type": "object",
	"properties": {
		"format_version": {
			"type": "number"
		},
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"identifier": {
			"type": "string"
		},
		"uuid": {
			"type": "string",
			"format": "regex",
			"pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
		},
		"version": {
			"type": "string",
			"format": "regex",
			"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
		},
		"dependencies": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"identifier": {
						"type": "string"
					},
					"version": {
						"type": "string"
					}
				},
				"anyOf": [
					{
						"required": [
							"identifier"
						]
					},
					{
						"required": [
							"uuid"
						]
					}
				],
				"required": [
					"version"
				]
			}
		}
	},
	"required": [
		"name",
		"identifier",
		"uuid",
		"format_version"
	]
}

=== Saturn-Labs/UnityFunkin/Assets/Resources/mod.json
{
    "$schema": "https://raw.githubusercontent.com/Saturn-Labs/UnityFunkin/refs/heads/main/Assets/Resources/Schemas/mod_descriptor_schema.json",
    "format_version": 0,
    "name": "CustomMod",
    "description": "This is a custom mod.",
    "identifier": "mod@ryd3v@custommod",
    "uuid": "f0d5f253-f75a-493c-9073-3b483eb027c8",
    "version": "1.0.0",
    "dependencies": [
        {
            "identifier": "mod@ryd3v@dependencymod",
            "version": ">=1.0.0 <1.1.0"
        }
    ]
}
